networks:
  app-network:
    driver: bridge

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip localhost,mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1data:/data/db
    networks:
      - app-network

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip localhost,mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2data:/data/db
    networks:
      - app-network

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip localhost,mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3data:/data/db
    networks:
      - app-network

  mongo-setup:
    image: mongo:latest
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: ["/bin/bash", "/scripts/init-mongo.sh"]
    volumes:
      - ./configuration/mongo/mongo-entrypoint.sh:/scripts/init-mongo.sh
    networks:
      - app-network

volumes:
  mongo1data:
  mongo2data:
  mongo3data: